[app]
app1 ansible_host=192.168.56.11
app1 ansible_user=vagrant
app1 ansible_ssh_private_key_file=/home/vagrant/projet-fils-rouge/.vagrant/machines/app/virtualbox/private_key

[odoo]
odoo1 ansible_host=192.168.56.12
odoo1 ansible_user=vagrant
odoo1 ansible_ssh_private_key_file=/home/vagrant/projet-fils-rouge/.vagrant/machines/odoo/virtualbox/private_key